/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainWindow.h"
#include "globals.h"

//==============================================================================
class BlipZonesApplication  : public JUCEApplication
{
public:
    //==============================================================================
    BlipZonesApplication()
    {
    }

    ~BlipZonesApplication()
    {
    }

    //==============================================================================
    void initialise (const String& commandLine)
    {
      // Do your application's initialisation code here..

    // Do your application's initialisation code here..
      init();
      setup();
      blipbox.config.touchscreen_x_min = 0;
      blipbox.config.touchscreen_y_min = 0;
      blipbox.config.touchscreen_x_range = 1023;
      blipbox.config.touchscreen_y_range = 1023;

      mainWindow = new MainAppWindow();
      blipbox.leds.setLed(0, 0, 255);
    }

    void shutdown()
    {
        // Do your application's shutdown code here..
      mainWindow = 0;
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        quit();
    }

    //==============================================================================
    const String getApplicationName()
    {
      return T("BlipZones");
    }

    const String getApplicationVersion()
    {
        return T("1.0");      
//         return ProjectInfo::versionString;
    }

    bool moreThanOneInstanceAllowed()
    {
        return true;
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        
    }

private:

  ScopedPointer <MainAppWindow> mainWindow;

};


//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(BlipZonesApplication)
