/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#ifndef __MAINWINDOW_H_30D86307__
#define __MAINWINDOW_H_30D86307__

#include "juce.h"


#include "PresetComponent.h"

 #define JUCE_LEAK_DETECTOR(OwnerClass)  public:\
			  static void* operator new (size_t sz)	   { return JUCE_NAMESPACE::juceDLL_malloc ((int) sz); } \
			  static void* operator new (size_t, void* p)	 { return p; } \
			  static void operator delete (void* p)	   { JUCE_NAMESPACE::juceDLL_free (p); } \
			  static void operator delete (void*, void*)	  {}

#define JUCE_DECLARE_NON_COPYABLE(className) \
	className (const className&);\
	className& operator= (const className&)

/** This is a shorthand way of writing both a JUCE_DECLARE_NON_COPYABLE and
	JUCE_LEAK_DETECTOR macro for a class.
*/
#define JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(className) \
	JUCE_DECLARE_NON_COPYABLE(className);\
	JUCE_LEAK_DETECTOR(className)

//==============================================================================
class MainAppWindow   : public DocumentWindow
{
public:
    //==============================================================================
    MainAppWindow();
    ~MainAppWindow();

    void closeButtonPressed();


    /* Note: Be careful when overriding DocumentWindow methods - the base class
       uses a lot of them, so by overriding you might break its functionality.
       It's best to do all your work in you content component instead, but if
       you really have to override any DocumentWindow methods, make sure your
       implementation calls the superclass's method.
    */

private:
    PresetComponent* preset;
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE (MainAppWindow);
};


#endif  // __MAINWINDOW_H_30D86307__
