/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#ifndef __SIMWINDOW_H__
#define __SIMWINDOW_H__

#include "../JuceLibraryCode/JuceHeader.h"

#include "SimScreen.h"

//==============================================================================
class SimWindow   : public DocumentWindow
{
public:
    //==============================================================================
    SimWindow();
    ~SimWindow();

    void closeButtonPressed();

private:
    Component* sim;
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SimWindow)
};


#endif  // __SIMWINDOW_H__
